
version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run build-ghpages
          else
            npm run build
          fi
      - persist_to_workspace:
          root: ~/myapp
          paths:
            - dist/*
